# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.siddhaarth.com
title: Personal site of Sid Rajkumar
email: siddhaarth@gmail.com
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap
  - title: camera
    url: http://photography.siddhaarth.com
  - title: linkedin
    url: https://www.linkedin.com/in/siddhaarth22
  - title: facebook
    url: https://www.facebook.com/siddhaarth.rajkumar
  - title: instagram
    url: https://instagram.com/siddhaarth_rajkumar/
